version: "3"

dotenv: ['.env']

vars:
  FLAG_CONFIG: --config=$CONFIG_PATH

tasks:
  
  # init:
  #   desc: "Init developers instruments [deprecated]"

  run:
    desc: "Run main application"
    cmd: go run ./cmd/sso {{.FLAG_CONFIG}}

  lint:
    desc: "lint all files"
    cmd: fieldalignment -fix ./...
    ignore_error: true

  charm:
    desc: "Run charm application [deprecated]"
    cmd: go run ./cmd/charmlog

  val:
    desc: "Run val application [deprecated]"
    cmd: go run ./cmd/validator

  test:
    desc: "Tests app"
    cmd: go test -v -cover ./...

  build:
    desc: "Builds application"
    deps: [lint]
    cmds:
      - 'go build -o bin/ ./cmd/sso/main.go'
    sources:
      - ./*.go,
      - ./**/*.go

  dev:
    desc: "Build and start app with file listener (hot reload)"
    deps: [build]
    silent: true
    watch: true
    cmd: ./bin/main {{.FLAG_CONFIG}}
    sources: 
      - ./*.go,
      - ./**/*.go

