version: "3"

tasks:
  migrate:
    desc: "migrate DB"
    cmd: go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./migrations

  migrate-test:
    desc: "migrate test DB"
    cmd: go run ./cmd/migrator --storage-path=./storage/sso.db --migrations-path=./tests/migrations --migrations-table=migrations_test
  
  run:
    desc: "Run main application"
    cmd: go run ./cmd/sso --config=./config/local.yaml

  test:
    desc: "Tests app"
    cmd: go test -v ./tests