version: "3"

dotenv: ['.env']

vars:
  FLAG_CONFIG: --config=$CONFIG_PATH

tasks:
  
  init:
    desc: "Init developers instruments [deprecated]"
    deps: [migrate]

  run:
    desc: "Run main application"
    cmd: go run ./cmd/sso {{.FLAG_CONFIG}}

  lint:
    desc: "lint all files"
    cmd: fieldalignment -fix ./...
    ignore_error: true
  
  ctx:
    desc: "Run ctx application [deprecated]" 
    cmd: go run ./cmd/context

  charm:
    desc: "Run charm application [deprecated]"
    cmd: go run ./cmd/charmlog

  val:
    desc: "Run val application [deprecated]"
    cmd: go run ./cmd/validator

  migrate:
    desc: "migrate DB"
    cmds:
      - go run ./cmd/migrator --storage-path=$STORE_PATH --migrations-path=./migrations

  test:
    desc: "Tests app"
    deps: [migrate-test]
    cmd: go test -v -cover ./...

  migrate-test:
    desc: "migrate test DB"
    cmd: go run ./cmd/migrator --storage-path=$STORE_PATH --migrations-path=./internal/tests/migrations --migrations-table=migrations_test

  build:
    desc: "Builds application"
    deps: [lint]
    cmds:
      - 'go build -o bin/ ./cmd/sso/main.go'
    sources:
      - ./*.go,
      - ./**/*.go

  dev:
    desc: "Build and start app with file listener (hot reload)"
    deps: [build]
    silent: true
    watch: true
    cmd: ./bin/main {{.FLAG_CONFIG}}
    sources: 
      - ./*.go,
      - ./**/*.go

