dotenv: ['../.env']

env: "dev" # dev, prod
store_path: ./storage/sso.db

services:

  authentication:
    token_ttl: 1h

servers:

  grpc:
    port: 44844
    timeout: 5s

  rest:
    port: 8080
    timeout: 5s